### ISSUE TITLE
Suggestion: Make makefile easier to edit

### ISSUE THREAD

**Issue by Lorenzooone** [devkitPro/nds-examples#17]
#### Overview:

Very simple changes to improve qol of users to the Makefiles.

#### Smaller Details: 

Taking the Hello World example, change INCLUDES to:
```
INCLUDES	:=	include $(BUILD)
```
Add this line below INCLUDES:
```
NAME_MAKEFILE := Makefile.arm9
```
Change $(BUILD) to:
```
$(BUILD):
	@[ -d $@ ] || mkdir -p $@
	@$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/$(NAME_MAKEFILE)
```

These changes should be applied to all the examples.

#### Nature of Request:  
- Addition

### Why would this feature be useful?
Makes it easier for users to know what to change if they have multiple Makefiles and build directories (for example due to a project being compiled on both NDS and GBA).

**Comment by fincs** [comment]
For cross platform projects, you may be interested in using devkitPro's CMake machinery instead. There are a few projects such as https://github.com/WinterMute/ansi-escape-demo and https://github.com/mtheall/ftpd that show how to build a single project for multiple platforms.

**Comment by Lorenzooone** [comment]
CMake in general is fine until you need to compile and embed resources when you build (and especially if you need to compile a program to compile the resources). Which is something you do for GBA and NDS. Then it becomes a real pain. You can see it in the (ftpd) project you linked as well.
So Makefiles are better for that.


It should be a really simple change, which also improves on the fact that there are hardcoded names (and one for which the variable already exists, in BUILD).
I understand it's a bit of a pain, but I think it would help users out. Even just in terms of having an example of not using hardcoded names.

**Comment by fincs** [comment]
devkitPro CMake provides several commands that make it really easy to embed resources into the binary, including resources generated by tools such as grit or mmutil. These commands are implicitly available when targetting devkitPro platforms.

https://github.com/devkitPro/pacman-packages/blob/master/cmake/common-utils/dkp-embedded-binary.cmake

Here's a quick example showing how to embed files into the executable, in a similar way to how it's done with classic devkitPro Makefiles:

```cmake
grit_add_binary_target(tilemap tilemap.png DEPTH 8 OPTIONS -mRtf)

dkp_add_embedded_binary_library(${PROJECT_NAME}_data
	font.bin
	tilemap # Targets generated by tools such as grit can be specified directly
)

target_link_libraries(${PROJECT_NAME} PRIVATE ${PROJECT_NAME}_data)
```
