### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by isage** [devkitPro/nds-examples#4]
I'm not sure if that should be reported against examples, but anyway.
None of the examples work with latest devkitARM on fat NDS with M3DSREAL.
Even hello_world just hangs on start.

**Comment by ltpour** [comment]
Not sure if this is related at all, but they also don't work on the DeSmuME core of Retroarch. All you get is a white screen.

**Comment by WinterMute** [comment]
The examples all run fine on hardware booted using https://github.com/devkitPro/nds-hb-menu/releases/latest, with the last DeSmuME binary from https://sourceforge.net/projects/desmume/files/desmume/0.9.11/  and no$gba from http://problemkaputt.de/gba.htm

Pirate menus have often been quite bad at booting homebrew unfortunately. Ideally you should find a replacement menu that works,

fwiw, if you copy akmenu4.nds & boot.nds from the hbmenu archive then boot akmenu4.nds from the m3dsreal menu then that should probably work, as long as it dldi patches.

**Comment by duckcantcode** [comment]
I'm running them on no$gba and it's saying the rom image crashed

**Comment by WinterMute** [comment]
> I'm running them on no$gba and it's saying the rom image crashed

Then report a bug to no$gba.

Also: please don't comment on issues that were closed 5 years ago.
